[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/:nickname"
  to = "/main.html?nickname=:nickname"
  status = 200

[[edge_functions]]
path = "/.netlify/functions/*"
function = "cached-faceit"
