name: Update Faceit Leaderboard

on:
  schedule:
    - cron: '0 */6 * * *'  # Co 6 godzin (UTC)
  workflow_dispatch:       # Możesz odpalić ręcznie z GitHub UI

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run update script
        run: node updateLeaderboard.js
        env:
          EDGE_CONFIG_ID: ${{ secrets.EDGE_CONFIG_ID }}
          EDGE_CONFIG_TOKEN: ${{ secrets.EDGE_CONFIG_TOKEN }}
          FACEIT_API_KEY: ${{ secrets.FACEIT_API_KEY }}
